## Uncaught exceptions
When no exception handler for a function can be found, std::terminate() is called and the application terminates. 

The call stack may or may not unwound. If the stack is not unwound, local variables will not be destoryed and any cleanup epected upon destruction of said variables will not happen.

## Catch-all handlers
C++ provides a mechanism to call all types of exceptions.

A **catch-all handler** works just like a normal catch block but uses the ellipses operator (...) as the type to catch.

The catch-all handler must be placed last in the catch block chain to ensure that exceptions can be caught by exception handlers tailored to specific data types.

```cpp
#include <iostream>

int main()
{
	try
	{
		throw 5; // throw an int exception
	}
	catch (double x)
	{
		std::cout << "We caught an exception of type double: " << x << '\n';
	}
	catch (...) // catch-all handler
	{
		std::cout << "We caught an exception of an undetermined type\n";
	}
}
```